
# This file is automatically generated, you probably don't want to edit this

seenByJudgeOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "seenByJudgeOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            Repr1 = NULL,
            Repr2 = NULL,
            Judge = NULL, ...) {

            super$initialize(
                package='DPACanalyses',
                name='seenByJudge',
                requiresData=TRUE,
                ...)
        
            private$..Repr1 <- jmvcore::OptionVariable$new(
                "Repr1",
                Repr1,
                permitted=list(
                    "nominal",
                    "nominaltext"))
            private$..Repr2 <- jmvcore::OptionVariable$new(
                "Repr2",
                Repr2,
                permitted=list(
                    "nominal",
                    "nominaltext"))
            private$..Judge <- jmvcore::OptionVariable$new(
                "Judge",
                Judge,
                permitted=list(
                    "nominal",
                    "nominaltext"))
        
            self$.addOption(private$..Repr1)
            self$.addOption(private$..Repr2)
            self$.addOption(private$..Judge)
        }),
    active = list(
        Repr1 = function() private$..Repr1$value,
        Repr2 = function() private$..Repr2$value,
        Judge = function() private$..Judge$value),
    private = list(
        ..Repr1 = NA,
        ..Repr2 = NA,
        ..Judge = NA)
)

seenByJudgeResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        debugText = function() private$..debugText,
        table = function() private$..table),
    private = list(
        ..debugText = NA,
        ..table = NA),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Representation seen by judge")
            private$..debugText <- jmvcore::Preformatted$new(
                options=options,
                name="debugText",
                title="Debug",
                visible=FALSE)
            private$..table <- jmvcore::Table$new(
                options=options,
                name="table",
                title="Counts",
                clearWith=list(
                    "Repr1",
                    "Repr2",
                    "Judge"),
                columns=list(
                    list(
                        `name`="Judge", 
                        `title`="Judge", 
                        `type`="text")))
            self$add(private$..debugText)
            self$add(private$..table)}))

seenByJudgeBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "seenByJudgeBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'DPACanalyses',
                name = 'seenByJudge',
                version = c(1,0,0),
                options = options,
                results = seenByJudgeResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' Representation seen by judge
#'
#' 
#' @param data .
#' @param Repr1 .
#' @param Repr2 .
#' @param Judge .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$debugText} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$table} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$table$asDF}
#'
#' \code{as.data.frame(results$table)}
#'
#' @export
seenByJudge <- function(
    data,
    Repr1,
    Repr2,
    Judge) {

    if ( ! requireNamespace('jmvcore'))
        stop('seenByJudge requires jmvcore to be installed (restart may be required)')

    options <- seenByJudgeOptions$new(
        Repr1 = Repr1,
        Repr2 = Repr2,
        Judge = Judge)

    results <- seenByJudgeResults$new(
        options = options)

    analysis <- seenByJudgeClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
