
# This file is automatically generated, you probably don't want to edit this

timeAnalysisOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "timeAnalysisOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            duration = NULL,
            judge = NULL,
            repr1 = NULL,
            repr2 = NULL,
            filter = NULL, ...) {

            super$initialize(
                package='DPACanalyses',
                name='timeAnalysis',
                requiresData=TRUE,
                ...)
        
            private$..duration <- jmvcore::OptionVariable$new(
                "duration",
                duration,
                permitted=list(
                    "continuous"))
            private$..judge <- jmvcore::OptionVariable$new(
                "judge",
                judge)
            private$..repr1 <- jmvcore::OptionVariable$new(
                "repr1",
                repr1)
            private$..repr2 <- jmvcore::OptionVariable$new(
                "repr2",
                repr2)
            private$..filter <- jmvcore::OptionNumber$new(
                "filter",
                filter,
                min=0)
        
            self$.addOption(private$..duration)
            self$.addOption(private$..judge)
            self$.addOption(private$..repr1)
            self$.addOption(private$..repr2)
            self$.addOption(private$..filter)
        }),
    active = list(
        duration = function() private$..duration$value,
        judge = function() private$..judge$value,
        repr1 = function() private$..repr1$value,
        repr2 = function() private$..repr2$value,
        filter = function() private$..filter$value),
    private = list(
        ..duration = NA,
        ..judge = NA,
        ..repr1 = NA,
        ..repr2 = NA,
        ..filter = NA)
)

timeAnalysisResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        debugText = function() private$..debugText,
        talk = function() private$..talk,
        table = function() private$..table,
        plot = function() private$..plot),
    private = list(
        ..debugText = NA,
        ..talk = NA,
        ..table = NA,
        ..plot = NA),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Time Analysis")
            private$..debugText <- jmvcore::Preformatted$new(
                options=options,
                name="debugText",
                title="Debug",
                visible=FALSE)
            private$..talk <- jmvcore::Preformatted$new(
                options=options,
                name="talk",
                title="",
                visible=FALSE)
            private$..table <- R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    general = function() private$..general,
                    judge = function() private$..judge,
                    repr = function() private$..repr),
                private = list(
                    ..general = NA,
                    ..judge = NA,
                    ..repr = NA),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="table",
                            title="Summary")
                        private$..general <- jmvcore::Table$new(
                            options=options,
                            name="general",
                            title="Overall",
                            columns=list(
                                list(
                                    `name`="N", 
                                    `title`="N", 
                                    `type`="integer"),
                                list(
                                    `name`="miss", 
                                    `title`="Missing", 
                                    `type`="integer"),
                                list(
                                    `name`="median", 
                                    `title`="Median", 
                                    `type`="number"),
                                list(
                                    `name`="sd", 
                                    `title`="sd", 
                                    `type`="number"),
                                list(
                                    `name`="min", 
                                    `title`="Min", 
                                    `type`="integer"),
                                list(
                                    `name`="max", 
                                    `title`="Max", 
                                    `type`="integer")))
                        private$..judge <- jmvcore::Table$new(
                            options=options,
                            name="judge",
                            title="Per judge",
                            visible=FALSE,
                            clearWith=list(
                                "judge"),
                            columns=list(
                                list(
                                    `name`="judge", 
                                    `title`="Judge", 
                                    `type`="text"),
                                list(
                                    `name`="N", 
                                    `title`="N", 
                                    `type`="integer"),
                                list(
                                    `name`="miss", 
                                    `title`="Missing", 
                                    `type`="integer"),
                                list(
                                    `name`="median", 
                                    `title`="Median", 
                                    `type`="number"),
                                list(
                                    `name`="sd", 
                                    `title`="sd", 
                                    `type`="number"),
                                list(
                                    `name`="min", 
                                    `title`="Min", 
                                    `type`="integer"),
                                list(
                                    `name`="max", 
                                    `title`="Max", 
                                    `type`="integer")))
                        private$..repr <- jmvcore::Table$new(
                            options=options,
                            name="repr",
                            title="Per representation",
                            visible=FALSE,
                            clearWith=list(
                                "repr1",
                                "repr2"),
                            columns=list(
                                list(
                                    `name`="repr", 
                                    `title`="Representation", 
                                    `type`="text"),
                                list(
                                    `name`="N", 
                                    `title`="N", 
                                    `type`="integer"),
                                list(
                                    `name`="miss", 
                                    `title`="Missing", 
                                    `type`="integer"),
                                list(
                                    `name`="total", 
                                    `title`="Total viewing time", 
                                    `type`="integer"),
                                list(
                                    `name`="median", 
                                    `title`="Median", 
                                    `type`="number"),
                                list(
                                    `name`="sd", 
                                    `title`="sd", 
                                    `type`="number"),
                                list(
                                    `name`="min", 
                                    `title`="Min", 
                                    `type`="integer"),
                                list(
                                    `name`="max", 
                                    `title`="Max", 
                                    `type`="integer")))
                        self$add(private$..general)
                        self$add(private$..judge)
                        self$add(private$..repr)}))$new(options=options)
            private$..plot <- R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    general = function() private$..general,
                    judge = function() private$..judge,
                    repr = function() private$..repr),
                private = list(
                    ..general = NA,
                    ..judge = NA,
                    ..repr = NA),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="plot",
                            title="Plot")
                        private$..general <- jmvcore::Image$new(
                            options=options,
                            name="general",
                            title="Overall",
                            renderFun=".generalPlot")
                        private$..judge <- jmvcore::Image$new(
                            options=options,
                            name="judge",
                            title="Per judge",
                            width=1000,
                            height=1000,
                            visible=FALSE,
                            renderFun=".judgePlot")
                        private$..repr <- jmvcore::Image$new(
                            options=options,
                            name="repr",
                            title="Per representation",
                            width=1000,
                            height=1000,
                            visible=FALSE,
                            renderFun=".reprPlot")
                        self$add(private$..general)
                        self$add(private$..judge)
                        self$add(private$..repr)}))$new(options=options)
            self$add(private$..debugText)
            self$add(private$..talk)
            self$add(private$..table)
            self$add(private$..plot)}))

timeAnalysisBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "timeAnalysisBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'DPACanalyses',
                name = 'timeAnalysis',
                version = c(1,0,0),
                options = options,
                results = timeAnalysisResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' Time Analysis
#'
#' 
#' @param data .
#' @param duration .
#' @param judge .
#' @param repr1 .
#' @param repr2 .
#' @param filter .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$debugText} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$talk} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$table$general} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$table$judge} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$table$repr} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plot$general} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot$judge} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot$repr} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
timeAnalysis <- function(
    data,
    duration,
    judge,
    repr1,
    repr2,
    filter) {

    if ( ! requireNamespace('jmvcore'))
        stop('timeAnalysis requires jmvcore to be installed (restart may be required)')

    options <- timeAnalysisOptions$new(
        duration = duration,
        judge = judge,
        repr1 = repr1,
        repr2 = repr2,
        filter = filter)

    results <- timeAnalysisResults$new(
        options = options)

    analysis <- timeAnalysisClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
