
# This file is automatically generated, you probably don't want to edit this

BTLanalysisOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "BTLanalysisOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            Repr1 = NULL,
            Repr2 = NULL,
            Selected = NULL,
            Judge = NULL,
            estIters = 4,
            epsCor = 0.003,
            rel = FALSE,
            plotScale = FALSE,
            plotGraph = FALSE,
            misfit = NULL, ...) {

            super$initialize(
                package='CJanalyses',
                name='BTLanalysis',
                requiresData=TRUE,
                ...)
        
            private$..Repr1 <- jmvcore::OptionVariable$new(
                "Repr1",
                Repr1,
                permitted=list(
                    "nominal",
                    "nominaltext"))
            private$..Repr2 <- jmvcore::OptionVariable$new(
                "Repr2",
                Repr2,
                permitted=list(
                    "nominal",
                    "nominaltext"))
            private$..Selected <- jmvcore::OptionVariable$new(
                "Selected",
                Selected,
                permitted=list(
                    "nominal",
                    "nominaltext"))
            private$..Judge <- jmvcore::OptionVariable$new(
                "Judge",
                Judge,
                permitted=list(
                    "nominal",
                    "nominaltext"))
            private$..estIters <- jmvcore::OptionInteger$new(
                "estIters",
                estIters,
                min=0,
                default=4)
            private$..epsCor <- jmvcore::OptionNumber$new(
                "epsCor",
                epsCor,
                min=0,
                default=0.003)
            private$..rel <- jmvcore::OptionBool$new(
                "rel",
                rel,
                default=FALSE)
            private$..plotScale <- jmvcore::OptionBool$new(
                "plotScale",
                plotScale,
                default=FALSE)
            private$..plotGraph <- jmvcore::OptionBool$new(
                "plotGraph",
                plotGraph,
                default=FALSE)
            private$..misfit <- jmvcore::OptionList$new(
                "misfit",
                misfit,
                options=list(
                    "none",
                    "Infit",
                    "Lz"))
        
            self$.addOption(private$..Repr1)
            self$.addOption(private$..Repr2)
            self$.addOption(private$..Selected)
            self$.addOption(private$..Judge)
            self$.addOption(private$..estIters)
            self$.addOption(private$..epsCor)
            self$.addOption(private$..rel)
            self$.addOption(private$..plotScale)
            self$.addOption(private$..plotGraph)
            self$.addOption(private$..misfit)
        }),
    active = list(
        Repr1 = function() private$..Repr1$value,
        Repr2 = function() private$..Repr2$value,
        Selected = function() private$..Selected$value,
        Judge = function() private$..Judge$value,
        estIters = function() private$..estIters$value,
        epsCor = function() private$..epsCor$value,
        rel = function() private$..rel$value,
        plotScale = function() private$..plotScale$value,
        plotGraph = function() private$..plotGraph$value,
        misfit = function() private$..misfit$value),
    private = list(
        ..Repr1 = NA,
        ..Repr2 = NA,
        ..Selected = NA,
        ..Judge = NA,
        ..estIters = NA,
        ..epsCor = NA,
        ..rel = NA,
        ..plotScale = NA,
        ..plotGraph = NA,
        ..misfit = NA)
)

BTLanalysisResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        debugText = function() private$..debugText,
        text = function() private$..text,
        table = function() private$..table,
        networkPlot = function() private$..networkPlot),
    private = list(
        ..debugText = NA,
        ..text = NA,
        ..table = NA,
        ..networkPlot = NA),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Bradley-Terry-Luce model and statistics")
            private$..debugText <- jmvcore::Preformatted$new(
                options=options,
                name="debugText",
                title="Debug",
                visible=TRUE)
            private$..text <- jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Bradley-Terry-Luce model")
            private$..table <- jmvcore::Table$new(
                options=options,
                name="table",
                title="Estimates",
                clearWith=list(
                    "Repr1",
                    "Repr2",
                    "Selected",
                    "Judge",
                    "estIters",
                    "epsCor"),
                columns=list(
                    list(
                        `name`="Repr", 
                        `title`="Representation", 
                        `type`="text"),
                    list(
                        `name`="Ability", 
                        `title`="Ability", 
                        `type`="number"),
                    list(
                        `name`="se", 
                        `title`="se", 
                        `type`="number")))
            private$..networkPlot <- jmvcore::Image$new(
                options=options,
                name="networkPlot",
                title="Comparisons plot",
                visible=FALSE,
                renderFun=".netPlot")
            self$add(private$..debugText)
            self$add(private$..text)
            self$add(private$..table)
            self$add(private$..networkPlot)}))

BTLanalysisBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "BTLanalysisBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'CJanalyses',
                name = 'BTLanalysis',
                version = c(1,0,0),
                options = options,
                results = BTLanalysisResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' Bradley-Terry-Luce model and statistics
#'
#' 
#' @param data .
#' @param Repr1 .
#' @param Repr2 .
#' @param Selected .
#' @param Judge .
#' @param estIters .
#' @param epsCor .
#' @param rel .
#' @param plotScale .
#' @param plotGraph .
#' @param misfit .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$debugText} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$table} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$networkPlot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$table$asDF}
#'
#' \code{as.data.frame(results$table)}
#'
#' @export
BTLanalysis <- function(
    data,
    Repr1,
    Repr2,
    Selected,
    Judge,
    estIters = 4,
    epsCor = 0.003,
    rel = FALSE,
    plotScale = FALSE,
    plotGraph = FALSE,
    misfit) {

    if ( ! requireNamespace('jmvcore'))
        stop('BTLanalysis requires jmvcore to be installed (restart may be required)')

    options <- BTLanalysisOptions$new(
        Repr1 = Repr1,
        Repr2 = Repr2,
        Selected = Selected,
        Judge = Judge,
        estIters = estIters,
        epsCor = epsCor,
        rel = rel,
        plotScale = plotScale,
        plotGraph = plotGraph,
        misfit = misfit)

    results <- BTLanalysisResults$new(
        options = options)

    analysis <- BTLanalysisClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
