
# This file is automatically generated, you probably don't want to edit this

numCompOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "numCompOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            group = NULL,
            alt = "notequal",
            varEq = TRUE, ...) {

            super$initialize(
                package='CJanalyses',
                name='numComp',
                requiresData=TRUE,
                ...)
        
            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep)
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group)
            private$..alt <- jmvcore::OptionList$new(
                "alt",
                alt,
                options=list(
                    "notequal",
                    "onegreater",
                    "twogreater"),
                default="notequal")
            private$..varEq <- jmvcore::OptionBool$new(
                "varEq",
                varEq,
                default=TRUE)
        
            self$.addOption(private$..dep)
            self$.addOption(private$..group)
            self$.addOption(private$..alt)
            self$.addOption(private$..varEq)
        }),
    active = list(
        dep = function() private$..dep$value,
        group = function() private$..group$value,
        alt = function() private$..alt$value,
        varEq = function() private$..varEq$value),
    private = list(
        ..dep = NA,
        ..group = NA,
        ..alt = NA,
        ..varEq = NA)
)

numCompResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        text = function() private$..text),
    private = list(
        ..text = NA),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="numComp")
            private$..text <- jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="numComp")
            self$add(private$..text)}))

numCompBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "numCompBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'CJanalyses',
                name = 'numComp',
                version = c(1,0,0),
                options = options,
                results = numCompResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' numComp
#'
#' 
#' @param data .
#' @param dep .
#' @param group .
#' @param alt .
#' @param varEq .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
numComp <- function(
    data,
    dep,
    group,
    alt = "notequal",
    varEq = TRUE) {

    if ( ! requireNamespace('jmvcore'))
        stop('numComp requires jmvcore to be installed (restart may be required)')

    options <- numCompOptions$new(
        dep = dep,
        group = group,
        alt = alt,
        varEq = varEq)

    results <- numCompResults$new(
        options = options)

    analysis <- numCompClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
