
# This file is automatically generated, you probably don't want to edit this

timeAnalysisOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "timeAnalysisOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            duration = NULL,
            Judge = NULL, ...) {

            super$initialize(
                package='CJanalyses',
                name='timeAnalysis',
                requiresData=TRUE,
                ...)
        
            private$..duration <- jmvcore::OptionVariable$new(
                "duration",
                duration,
                permitted=list(
                    "continuous"))
            private$..Judge <- jmvcore::OptionVariable$new(
                "Judge",
                Judge)
        
            self$.addOption(private$..duration)
            self$.addOption(private$..Judge)
        }),
    active = list(
        duration = function() private$..duration$value,
        Judge = function() private$..Judge$value),
    private = list(
        ..duration = NA,
        ..Judge = NA)
)

timeAnalysisResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        debugText = function() private$..debugText,
        judge = function() private$..judge),
    private = list(
        ..debugText = NA,
        ..judge = NA),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Time Analysis")
            private$..debugText <- jmvcore::Preformatted$new(
                options=options,
                name="debugText",
                title="Debug",
                visible=FALSE)
            private$..judge <- R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    table = function() private$..table),
                private = list(
                    ..table = NA),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="judge",
                            title="")
                        private$..table <- R6::R6Class(
                            inherit = jmvcore::Group,
                            active = list(
                                general = function() private$..general,
                                split = function() private$..split),
                            private = list(
                                ..general = NA,
                                ..split = NA),
                            public=list(
                                initialize=function(options) {
                                    super$initialize(
                                        options=options,
                                        name="table",
                                        title="")
                                    private$..general <- jmvcore::Table$new(
                                        options=options,
                                        name="general",
                                        columns=list(
                                            list(
                                                `name`="mean", 
                                                `title`="Mean", 
                                                `type`="number"),
                                            list(
                                                `name`="sd", 
                                                `title`="sd", 
                                                `type`="number"),
                                            list(
                                                `name`="min", 
                                                `title`="Min", 
                                                `type`="integer"),
                                            list(
                                                `name`="max", 
                                                `title`="Max", 
                                                `type`="integer")))
                                    private$..split <- jmvcore::Table$new(
                                        options=options,
                                        name="split",
                                        visible=FALSE,
                                        clearWith=list(
                                            "Judge"),
                                        columns=list(
                                            list(
                                                `name`="judge", 
                                                `title`="Judge", 
                                                `type`="text"),
                                            list(
                                                `name`="mean", 
                                                `title`="Mean", 
                                                `type`="number"),
                                            list(
                                                `name`="sd", 
                                                `title`="sd", 
                                                `type`="number"),
                                            list(
                                                `name`="min", 
                                                `title`="Min", 
                                                `type`="integer"),
                                            list(
                                                `name`="max", 
                                                `title`="Max", 
                                                `type`="integer")))
                                    self$add(private$..general)
                                    self$add(private$..split)}))$new(options=options)
                        self$add(private$..table)}))$new(options=options)
            self$add(private$..debugText)
            self$add(private$..judge)}))

timeAnalysisBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "timeAnalysisBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'CJanalyses',
                name = 'timeAnalysis',
                version = c(1,0,0),
                options = options,
                results = timeAnalysisResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' Time Analysis
#'
#' 
#' @param data .
#' @param duration .
#' @param Judge .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$debugText} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$judge$table} \tab \tab \tab \tab \tab a group \cr
#' }
#'
#' @export
timeAnalysis <- function(
    data,
    duration,
    Judge) {

    if ( ! requireNamespace('jmvcore'))
        stop('timeAnalysis requires jmvcore to be installed (restart may be required)')

    options <- timeAnalysisOptions$new(
        duration = duration,
        Judge = Judge)

    results <- timeAnalysisResults$new(
        options = options)

    analysis <- timeAnalysisClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
